import { z } from 'zod';

export const qunixThemeSettingsSchema = z.object({
  background_color: z.string().min(4).max(30),
  text_color: z.string().min(4).max(30),
  focus_color: z.string().min(4).max(50),
  shadow_opacity: z.number().min(0).max(1),
  font_family: z.string().min(1).max(100),
  sidebar_color: z.string().min(4).max(30),
  card_color: z.string().min(4).max(30),
  border_color: z.string().min(4).max(50),
  border_radius: z.number().min(0).max(100),
  navbar_color: z.string().min(4).max(30),
  terminal_color: z.string().min(4).max(30),
  terminal_text_color: z.string().min(4).max(30),
  input_color: z.string().min(4).max(30),
  button_radius: z.number().min(0).max(100),
  input_radius: z.number().min(0).max(100),
  card_radius: z.number().min(0).max(100),
  navbar_height: z.number().min(32).max(200),
  sidebar_item_gap: z.number().min(0).max(100),
  sidebar_animation: z.boolean(),
  background_image: z.string().optional(),
  sidebar_blur: z.number().min(0).max(50),
  wallpaper_blur: z.number().min(0).max(50),
  wallpaper_brightness: z.number().min(0).max(1),
  glass_transparency: z.number().min(0).max(100),
  editor_color: z.string().min(4).max(30),
  editor_text_color: z.string().min(4).max(30),
  listing_color: z.string().min(4).max(30),
  button_color: z.string().min(4).max(30),
});
